spring:
  devtools:
    restart:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: qudtngogo1!
    hikari:
      poolName: HikariCP
      connectionTimeout: 30000
      maximumPoolSize: 10

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz:
        scheduler:
          instanceName: quartz-scheduler
          instanceId: AUTO
          instanceIdGenerator.class: org.quartz.simpl.SimpleInstanceIdGenerator
          threadName: quartz-manager-thread
        threadPool:
          threadCount: 20
        jobStore:
          useProperties: true
          misfireThreshold: 60000
          tablePrefix: QRTZ_
          isClustered: true
        plugin:
          shutdownHook:
            class: org.quartz.plugins.management.ShutdownHookPlugin
            cleanShutdown: false

#springdoc:
#  api-docs:
#    path: /api-docs

server:
  port: 8080

logging:
  level:
    root: info
    org:
      bys:
        sample: debug


api-package: com.bys.sample.quartz.controller
application.name: quarts-controller
application.description: Quartz Scheduler using Rest API with Spring Boot
